### ISSUE TITLE
Inventurliste als CSV-Export

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#1010]
**Spalten**
* [x] Artikelnummer
* [x] Name
* [x] Einheit
* [x] Hersteller
* [x] aktueller Lagerstand
* [x] Verkaufspreis (Brutto)
* [x] multiplizierter Preis (nur wenn Lagerstand positiv)
* [x] Falls Einkaufspreise aktiviert sind, dann Netto-Preis und summe von EP)

**Todos**
* [x] Varianten als extra Zeile
* [x] Als Datei speichern - utf8?
* [x] In Seite integrieren (Aktionen) - nur mit Häkchen (ausgewählte Produkte)
* [x] Nur Lagerprodukte berücksichtigen?
* [x] Changelog
