### ISSUE TITLE
jQuery-UI Dialog und Featherlight Dialog ersetzen mit Bootstrap Modal

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#328]
jQuery-UI ist in die Jahre gekommen, ersetzen mit https://getbootstrap.com/docs/4.0/components/modal/

**Ziele**
* Vereinheitlichung aller verwendeten Modals (Dialoge)
* modernes Design (auch mobil), verbesserte Usability
* nur noch eine Dependency verwenden (bessere Wartbarkeit)

Achtung: jQuery-UI Dependency noch nicht löschen (Datepicker, Draggable werden weiterhin verwendet)

**todos code cleaning**
* [x] option "alle mitglieder" weggeben bei "auf mitglied umbuchen"
* [x] css: .ui-dialog, #product-name-edit-form löschen
* [x] remove Helper.appendFlashMessageToDialog, admin.bindToggleQuantityQuantity, Admin.addDatepickerInDialog

**done in #524, #530 and #537**
* [x] Allgemein: Abmelden
* [x] Netzwerk-Modul: Produkte wirklich synchronisieren
* [x] Warenkorb: Wirklich vergangenen Warenkorb laden
* [x] Mitglied: Status, Kommentar, Gruppe ändern
* [x] Guthaben, Pfand, Mitgliedsbeitrag eintragen
* [x] Guthaben, Pfand, Mitgliedsbeitrag löschen
* [x] Bestellungen: Abholtag ändern, Alle Produkte abgeholt, auf anderes Mitglied umbuchen, Anzahl, Preis, Stornieren, Gewicht, Sofort-Bestellung, Sofort-Bestellung abbrechen, Als PDF generieren
* [x] Upload: Produkt, Hersteller, Blog-Artikel, Slider, Mitglieds-Profilbild, Kategorie, AGB File-Upload, Produkt-Bild löschen
* [x] featherlight dependency löschen
* [x] Bild-Vergrößern-Funktion
* [x] Produkt: Neues Produkt anlegen, Name und Beschreibung ändern, Kategorien, Anzahl, Preis, Steuersatz, Lieferrhythmus, Variante hinzufügen, Variante löschen, Standard-Variante ändern, Lagerprodukt, Pfand eintragen, Status, Neu?, Produkt löschen
* [x] Cookie-Overlay bei Login, Nutzungsbedingungen bei Registrierung, AGB bei "Warenkorb abschließen"
* [x] Mitgliedskonto löschen
* [x] Stundenabrechnungs-Modul: Zahlung löschen
* [x] Screenshots Doku austauschen

**Zusätzliche Verbesserungen in #524, #530 und #537**
* Sofort-Bestellung: Mitgliedsnamen im Dropdown ist nun filterbar
* Variante zu Produkt hinzufügen: Varianten im Dropdown sind nun filterbar
* Kategorien: Ober-Kategorie(n) ist (sind) nun automatisch mitausgewählt, wenn nur die Unterkategorie angeklickt wird. Es werden auch automatisch alle Unterkategorien entfernt, wenn eine Oberkategorie entfernt wird.
* Name und Beschreibung eines neuen Produktes können direkt beim Anlegen eingegeben werden.
