### ISSUE TITLE
Implement integration tests with IntegrationTestTrait

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#404]
Since v3.7 CakePHP provides IntegrationTestTrait which is really great!

This refactoring
* should make the tests quicker
* reduces code - as methods (eg. assert methods) from the cake core are used

**Todos**

**done**
* [x] netzwerk modul testen
* [x] remove html output in SendShells (unit tests break on travis)
* [x] rechnngs-download geht nicht: https://demo-de.foodcoopshop.com/admin/action-logs?types=&types%5B%5D=cronjob_send_invoices&customerId=&productId=&dateFrom=06.05.2020&dateTo=03.08.2020
* [x] open order lists inline in browser and do not force download
* [x] PaymentsController: file upload not yet working
* [x] Changelog: speed up travis integration testing by 50%!
* [x] ListsController: link with path in order_lists.php (wrong), tests not yet working
* [x] as the new LoginTrait just fakes a login (to be quick), the "real" login needs to get an own test
* [x] Wrap up             'headers' => [                'X_REQUESTED_WITH' => 'XMLHttpRequest',                'ACCEPT' => application/json'           ],
* [x] do not show stack trace: ProductsControllerTest.php:257
* [x] InstantOrderTests are not working (no AppSession in AppAuth)
* [x] AppCakeTestCase should contain much less assertMethods. Use the built-in assert-methods in IntegrationTestCase.
* [x] remove usage of httpClient in all tests
* [x] HttpClient removed: BlogPostControllerTest (#529), ManufacturersFrontendController, ProductsFrontendController (#531)
* [x] CartControllerTest::testAddLoggedOut fails due to missing exit on autorization
* [x] CartController authorize does not work any more
* [x] ProductsControllerTest::testDeleteProduct fails
* [x] Refactor CartsControllerTest
* [x] Refactor OrderDetailsControllerAddFeedbackTest
* [x] Refactor OrderDetailsControllerCancellationTest.php
* [x] Refactor OrderDetailsControllerEditAmountTest.php
* [x] Refactor OrderDetailsControllerEdittCustomerTest.php
* [x] Refactor OrderDetailsControllerEditPickupDayTest
* [x] Refactor OrderDetailsControllerEditPriceTest
* [x] Refactor OrderDetailsControllerEditQuantityTest
* [x] addProductToCart() and finishCart without httpClient
* [x] enable testCancellationWithTimebasedCurrency
* [x] if (!$_SERVER['REQUEST_METHOD'] == 'POST') { is not set with IntegrationTest
* [x] testNewPasswordRequestWithValidEmail test login with new password

**Comment by dpakach** [comment]
@mrothauer 
I was trying to implement tests using the `IntegrationTestTrait` but I am having a problem when trying to refactor the tests with post method.
The basic problem I see is in 
https://github.com/foodcoopshop/foodcoopshop/blob/f8952efb0773c92cc6013ba6aae095e61c51d3b0/templates/Error/errorjson.php#L16

Since there is `exit;` the test just exits after it reaches that line and the whole test execution stops.
It seems like that line is executed when there is error.

for eg. When you want to test add to product cart when the user is not logged in then the execution reaches that line and just exits without proceeding to other tests.
Do you have any idea how to handle this or workaround for this?

**Comment by mrothauer** [comment]
I found out, that the default layout is rendered if `exit` removed. You need to tell the controller to render another layout that just echos the content, like /templates/layout/ajax.php

Adding `$this->viewBuilder()->setLayout('ajax');` in line 189 of AppController should do the trick, after that `exit` in the layout can be removed.

**Comment by dpakach** [comment]
@mrothauer, how do you check for flash messages with the `IntegrationTestTrait`. 
The flash messages are not in the response body like it used to.
There seems to be an option `$this->enableRetainFlashMessages();` and another to check `$this->assertFlashMessage()`. But this is not working for me right now.

**Comment by mrothauer** [comment]
@dpakach 

> The flash messages are not in the response body like it used to.

They should be available in the response body - in which test are they missing?

Working example:
https://github.com/foodcoopshop/foodcoopshop/blob/2d932330923a58c0d2ad22bdd32c202011573acc/tests/TestCase/src/Controller/ProductsFrontendControllerTest.php#L81

You should not need `$this->enableRetainFlashMessages()` as we can assert the rendered html output.
see https://book.cakephp.org/3/en/development/testing.html#testing-flash-messages
