### ISSUE TITLE
Zweiwöchige Lieferrhythmen nur in der Woche vor der Abholung bestellbar machen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#716]
Zweiwöchige Produkte sind ab sofort immer nur in der Woche vor dem Abholtag bestellbar. In der anderen Woche ist das Produkt ausgeblendet. Ist für die Mitglieder einfacher zu verstehen.

3, 4wöchig und 1. 2. 3. 4. und letzter Freitag im Monat und Sammelbestellungen sollen weiterhin auch in Vorwochen bestellbar bleiben.

**todos**
* [x] Produkte mit zweiwöchigem Lieferrhythmus im Produktkatalog ausblenden (Lieferpause anzeigen wäre schöner, aber technisch schwieriger umzusetzen)
* [x] In Sofort-Bestellung immer anzeigen
* [x] Changelog / Docs updaten

**offen**
* [ ] Validierung bei Warenkorb-Abschluss + Unit-Test
* [ ] Validierung bei addToCart + Unit-Test

Validerungs-Tests sind schwierig, weil das Datum beim Bestellen in den Tests nicht gesetzt werden kann.
