### ISSUE TITLE
Gutscheine verkaufen und einlösen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#760]
Siehe https://foodcoopshop.github.io/de/dorfladen-online-gutscheine.html

**todos**
* [x] Bei bestellten Produkten negativen Preis zulassen (Validierung anpassen)
* [x] EP im Nachhinein anpassen, auch negativ zulassen
* [x] Name von bestellten Produkten editierbar machen für Gutscheinnummer (Feedback-Funktion deaktivieren?)
* [x] Negativen Preis auch rot anzeigen?
* [x] Dokumentation
* [x] Unit Test
* [x] Rechnungen testen aber müsste passen
* [x] Blog-Artikel auf FB posten sobald online
* [x] PR-ID anpassen im Changelog
