### ISSUE TITLE
Weitere Cache-Optimierungen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#763]
**todos**
* [ ] nochmal genauer testen: FileCache vs. Redis vs. Memcached
* [ ] afterSave bzw. afterDelete Callback auf isDirty checken (cache nicht löschen, wenn zb. firstname bei hersteller geändert wird, aber schon löschen, wenn zb. delivery_break geändert wird)
* [ ] nicht immer den kompletten cache löschen (productId) - wenn nur ein Produkt geändert wird
* [ ] Blog-Artikel cachen und ggfs. in html nachladen
