### ISSUE TITLE
Bootstrap Select mit Select2 tauschen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#773]
Bootstrap select is very badly maintained, so after waiting more than 8 months for a new release I decided to replace the dependency

Update 12.01.2022: Refactoring on ice... not so easy :-) and not super-urgent.

**todos**
* [ ] multiselect close on select geht nicht
* [ ] andere darstellung für tags bei multiple
* [ ] "alle produkte" option fehlt nach ajax
* [ ] schmale inhalte nicht breiter machen als notwendig (zb. gruppieren nach) - auto width + max-width
* [ ] einbindung evtl. generalisieren .select2(
* [ ] disable specific ids (hofladen-online)
* [ ] admin/ seiten: layout dropdown in header
* [ ] global setting for theme $.fn.select2.defaults.set("theme", "classic");

**es sind plötzlich alle dropdowns select2 dropdowns**
* [ ] hersteller-einstellungen steuersatz)
* [ ] selbstbedienung dropdown layout
* [ ] initiieren in eg. form noch ohne bootstrap-select-class

**später**
* [ ] fileupload test
* [ ] mobil testen
* [ ] Changelog

**done**
* [x] ajax: suche funktioniert nicht: https://stackoverflow.com/questions/60438505/select2-load-data-once-from-remote-but-perform-search-on-client
* [x] modal (umbuchen): such-feld nicht befüllbar
* [x] multiselect (action logs, lieferpause)
* [x] ajax data source for products
* [x] ajax: preselect
* [x] ajax data source for customers
* [x] einbindung in modals testen (mitglied umbuchen, sofort-bestellung)
* [x] locale setzen (no results found)
* [x] wenn ausgewähltes element zu lang, ist pfeil nach unten im text
* [x] breiteres und höheres dropdown (aufgeklappt)
* [x] completely remove bootstrap select
* [x] install select2
* [x] update bootstrap to v5 (modal-refacoring)
* [x] modal closer wrong layout
* [x] layout adaptions: https://github.com/apalfrey/select2-bootstrap-5-theme
* [x] schriftgröße in liste
* [x] form padding filter-options
* [x] Failed asserting that '2022-01-09 16:08:05 warning: Warning (2): Undefined variable $customersForDropdown in [/home/runner/work/foodcoopshop/foodcoopshop/plugins/Admin/templates/element/payment/csvUpload.php, line 88]

**nice to have**
* [ ] ajax cache https://stackoverflow.com/questions/26466788/select2-ajax-search-remember-last-results
* [ ] ajax: loader bei preselect und nach click
