### ISSUE TITLE
E-Mail-Versand aller E-Mails auf Queue umstellen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#842]
* Der Mailversand macht immer wieder Probleme. Das alles ist schwer zu debuggen, weil die Mailserver der Installationen unterschiedlich sind.
* Evtl. läuft das dann wieder: https://github.com/foodcoopshop/foodcoopshop/issues/825
* Lösung (wie auch schon beim Bestelllisten-Versand) könnte ein generelles Umstellen aller E-Mails auf die Queue sein.
* Angenehmer Nebeneffekt: Schnellere Requests für den User.

**todos**
* [x] Errors werden in Github Action Unit Tests angezeigt (vorher nicht)
* [x] mediumtext: info an dereuromark, migration für queue?
* [x] 2x Lieferschein versenden mit SMTP-Fehler zerschießt Tooltip
* [x] falsche transport-config auf demo.dorfladen-online.at versendet trotzdem. default-transport wird aber verwendet (lokal)

**wenn alles funktioniert**
* [x] migration guide anpassen
* [x]  doku anpassen (fallback-config wurde entfernt)
* [x] fallback config aus globalen overrides raus

**done**
* [x] alle demo-seiten umstellen und laufen lassen
* [x] Ruft sich bei Fehler immer wieder selbst auf
* [x] SendInvoiceToCustomerTask
* [x] SendOrderListTask
* [x] SendInvoiceToManufacturerTask
* [x] SendDeliveryNoteTask
* [x] fallback weg? (credentials)
* [x] worker soll permanent laufen
* [x] error mails werden nicht versendet
* [x] transport and profile for BackupDatabaseShell - scheint ohne zutun zu funktionieren
* [x] was ist mit emailversand von order lists und invoices (bereits von queue aus getriggert)
* [x] ist getOriginalSubject wenn replaced das richtige?
* [x] longtext (migration)
* [x] pdfs können nicht geöffnet werden (jpg geht)
* [x] CustomersFrontendControllerTest::testNewPasswordRequestWithValidEmail
* [x] kein output bei tests - exitwhennothingtodo
* [x] tabelle queued_jobs nicht backupen
* [x] tests anpassen: queue trait in appCaketestcase - überall sonst raus
* [x] was ist mit backup-emails: tabelle queued_jobs nicht backupen
