### ISSUE TITLE
Lieferrhythmus erweitern: Letzter Liefertag

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#847]
Bei "normalen wöchentlichen" Produkten wäre es super, wenn man einstellen kann, bis wann es aktiv sein soll und dann automatisch deaktiviert wird.

Beispiel von Tante Regina: Schafjoghurt ist den ganzen Juni verfügbar... Das müssen wir uns dann immer wo aufschreiben wann wir’s deaktivieren müssen.. und über mehrere Wochen mit Sammelbestellung hilft da auch nicht.

**Todos**
* [ ] Migration erstellen
* [ ] Overlay anpassen
* [ ] Netzwerk-Modul testen
* [ ] Unit Tests erweitern

** Fragen**
* [ ] auch für andere Lieferrhythmen sinnvoll?
