### ISSUE TITLE
Anpassungen Migrations

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#882]
**todos**
* [x] deploy: `bin/cake migrations migrate --source Migrations/prepare-for-update-from-v3.5` einmalig ausführen

```
//$table->insert($data)->save();

     $texts = [
            'de_DE' => 'Präfix für Rechnungs-Nummernkreis<br /><div class="small">Max. 6 Zeichen inkl. Trennzeichen.</div>',
            'en_US' => 'Prefix for invoice numbers<br /><div class="small">Max. 6 chars incl. separator.</div>',
        ];
        $table = $this->table('fcs_configuration');
        $table->setData([
            [
                'name' => 'FCS_INVOICE_NUMBER_PREFIX',
                'type' => 'readonly',
                'value' => 600,
                'position' => 3600,
                'active' => APP_ON,
                'text' => $texts[I18n::getLocale()],
                'locale' => I18n::getLocale(),
            ],
        ]);
        $table->saveData();
```

**done**
* [x] init-migration erzeugen mit [snapshot-tool](https://book.cakephp.org/migrations/3/en/index.html#generating-migrations-from-an-existing-database)
* [x] migrations automatisch ausführen: zuerst -p Queue, dann normal
* [x] unit-tests bootstrap: [Migrations für Test-Datenbank automatisch ausführen](https://book.cakephp.org/4/en/development/testing.html#creating-test-database-schema)
* [x] [automatisches seeding](https://book.cakephp.org/migrations/3/en/index.html#seed-seeding-your-database)  test-datenbank
* [x] docker test-db volumes anpassen
* [x] anpassungen für test-datenbank in seeds (auch automatisch ausführen)
* [x] aus test-db-data.sql eine seed-datei erzeugen (schneller)
* [x] phinxlogs aus test-db.sql raus
* [x] seeds für de / en - doku updaten
* [x] phinxlogs raus für alte installations
* [x] neuinstallationen / updates: init-migrations nicht erneut ausführen (oder eh egal), bestehende phinx-einträge löschen
* [x] ersetzte sql dateien löschen (dokus: links weggeben)
* [x] dokus anpassen (.sql überall weg), `migrations migrate` und `migrations seed`
* [x] test: wenn sich struktur ändert, laufen tests noch?
