### ISSUE TITLE
Kundendaten für Hersteller anonymisieren #2

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#929]
**Bestelllisten / Rechnungen**
* [x] Superadmins brauchen Klarnamen in Listen:  statt 2 (gruppiert nach produkt / mitglied) immer 4 listen (jeweils anonymisiert und im klartext) generieren
* [x] entsprechend der rolle (hersteller, superadmin) dann die jeweiligen listen anzeigen => (Zusätzliche Sub-Folder "anonymized", "non-anonymized" - auch bei rechnungen. für superadmin beide möglichkeiten anzeigen, für hersteller die jeweils aktivierte
* [x] Auch für das dynamische Generieren der Bestelllisten (Bestellliste prüfen) immer 4 Optionen anzeigen (Für Rechnungen nicht notwendig)
* [x] Changelog
* [x] Bestelllisten: 4 Links anzeigen
* [x] Bestelllisten prüfen: 4 Links anzeigen
* [x] Bestelllisten: Für Hersteller nur die relevanten anzeigen
* [x] In eine Zeile packen für Superadmins
* [x] Zugriffsrechte: Hersteller dürfen nur auf Bestellungen mit ihrer Einstellung zugreifen
* [x] Generieren von Bestelllisten: 4x generieren
* [x] Unit Tests

**Todos**
* [x] anonymizeCustomersForManufacturersEnabled entfernen
* [x] Blog-Beitrag
