### ISSUE TITLE
Bearbeiten von Produkten über Excel-Export und -Import

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#973]
Follow-Up von #953 

**Workflow für Bearbeiten von Produkten**
* [ ] Produkt-Liste über neuen Link downloaden, dann in Excel öffnen und editieren, dann wieder uploaden
* [ ] Die Zuordnung erfolgt über die Produkt-ID
* [ ] Named Parameters für create-Methode?
* [ ] Preis nach Gewicht (1,4/250g/100g)?
* [ ] Lagerprodukt ja/nein
* [ ] Strategie für alle StockAvailable-Felder in CSV
* [ ] Strategie für Varianten

**Todos Prio 2**
* [ ] Falls Daten valide: Vorschau der Produkte mit Bestätigen-Button
* [ ] ProductReader::formatColumns auch über ProductEntity-Setter laufen lassen (z.B. auto-format auf float von preis, <script>-tag weg
* [ ] Kategorien und Varianten als Admin / Superadmin anlegen, bei Herstellern nicht
* [ ] Leerzeilen sollen automatisch ignoriert werden (Info aus Doku kann dann raus)
