### ISSUE TITLE
Paginierung für Produkt-Seiten

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#999]
* Die "Alle Produkte"-Seite ist recht langsam, wird aber natürlich oft angeklickt
* max 50 Produkte anzeigen
* Cake-Paginierung kann nicht verwendet werden, da Products kein ResultSet ist, sondern ein Array (historisch bedingt...). Das zu ändern ist nicht so einfach.

**todos**
* [x] Paginierung in CatalogService verankern
* [x] Blätter-Links erstellen
* [x] Formatierung der Blätter-Links (auch mobil + dark mode)
* [x] Einbauen in NewProducts / Manufacturers-Detail, Categories-Detail
* [x] Testen: Selbstbedienungs-Modus
* [x] Übersetzungen
* [x] "xx gefunden" rechts anpassen
* [x] Anzahl stimmt noch nicht wenn Caching an ist
* [x] Changelog
* [x] Seite x von y / Anzahl Produkte
* [x] 404 wenn Produkte weniger werden und page=5 z.B. keine Daten mehr liefert
* [x] Tests erweitern
